name: calm_campus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
table_calendar: ^3.1.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  sqflite: ^2.3.3+1
  image_picker: ^1.0.7
  crop_your_image: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  just_audio: ^0.9.42
  equatable: ^2.0.5
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  #flutter_native_timezone_updated_gradle: ^2.0.3
  intl: ^0.19.0
  supabase_flutter: ^2.10.3
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.10
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/ambient/
    - assets/audio/guided/
    - assets/lang/
    - assets/photo/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/photo/CalmCampus-App-Icon-Dark.png"
  adaptive_icon_foreground: "assets/photo/CalmCampus-App-Icon-Dark.png"
  adaptive_icon_background: "#FFFFFF"
