name: calm_campus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
table_calendar: ^3.1.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.3.3
  just_audio: ^0.9.42
  equatable: ^2.0.5
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_native_timezone_updated_gradle: ^4.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/ambient/
    - assets/audio/guided/
